name: Padavan固件编译

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置编译固件的型号，用空格符分隔：
        default: "PSG1218"
        required: false
      cloneurl:
        description: 设置源码链接地址，注意后加.git：
        default: "https://github.com/hanwckf/rt-n56u.git"
        required: false  
      release:
        description: 是否需要发布到Release？(不发布也可以到Artifacts下载)
        default: 'yes'
        required: false
        
env: 
  TNAME: "${{ github.event.inputs.production }}"    # 路由型号

jobs:
  padavan:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id     # 监视所有者点击start
    steps:

    - name: 生成版本号
      run: |
        whoami
        id
        VERSION=$(TZ='Asia/Shanghai' date '+%Y/%m/%d %H:%M')
        val1=$(echo $TNAMES | sed 's/ /-/')
        echo "NAME=$VERSION-${val1}" >> $GITHUB_ENV
        echo "TAG=Padavan-${val1}" >> $GITHUB_ENV
        ip addr
        
    - name: 下载源码
      run: |
        sudo mkdir -m 777 -p /opt/images/
        echo 开始编译时间： >> /opt/images/readme.txt
        TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S' >> /opt/images/readme.txt
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u > /dev/null
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh > /dev/null
        pwd
