name: Padavan 手动云编译

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置固件型号，多个型号间用空格符分隔：
        default: "PSG1218"
        required: false
      cloneurl:
        description: 设置源码链接地址，注意后加.git：
        default: "https://github.com/hanwckf/rt-n56u.git"
        required: false
      release:
        description: 发布到Release？否则到Artifacts下载：
        default: 'yes'
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: 同步主存储库
      uses: actions/checkout@master
      
    - name: 初始环境设置
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin  > /dev/null

    - name: 生成版本号
      run: |
        whoami
        id
        val3=$(TZ='Asia/Shanghai' date +%Y.%m.%d-%H%M)
        echo "DATE=$val3" >> $GITHUB_ENV
        val1="${{ github.event.inputs.production }}"
        val2=$(echo $val1 | sed 's/ /-/')
        echo "NAME=$val3+${val2}" >> $GITHUB_ENV
        echo "TAG=v$val3+${val2}" >> $GITHUB_ENV
        ip addr

    - name: 下载源码
      run: |
        sudo mkdir -m 777 -p /opt/images/
        echo 开始编译时间： >> /opt/images/readme.txt
        TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S' >> /opt/images/readme.txt
        git clone --depth=1 ${{ github.event.inputs.cloneurl }} /opt/rt-n56u > /dev/null
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh > /dev/null
        pwd

    - name: 自定义配置
      run: |
        for m in ${{ github.event.inputs.production }}; do
          cp -f $m/$m.config /opt/rt-n56u/trunk/configs/templates/$m.config
          echo "$m.config 拷贝完成。"
          cp -f $m/$m.sh /opt/rt-n56u/trunk
          echo "$m.sh 拷贝完成。"
        done

    - name: 开始编译
      run: |
        cd /opt/rt-n56u/trunk
        for m in ${{ github.event.inputs.production }}; do
          cp -f ./configs/templates/$m.config .config
          echo "$m.config 修改插件模板完成。"
          sudo chmod +x ./$m.sh
          sudo ./$m.sh
          echo "$m.sh 自定义设置成功。"
        done
